version: '3.3'

services:
  st-template:
    image: 9e3u2f0b1/st-template:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - node_modules:/usr/app/node_modules

volumes:
  node_modules:
